#pragma once

#include "stdafx.h"

enum CLIENT_MESSAGES {
	CLI_MESS_ALLOC_ERROR,
	CLI_MESS_WARN,
	CLI_MESS_STACK_EMPTY,
	CLI_MESS_STACK_EMPTY_EXIT,
	CLI_MESS_WRONG_TYPE,
	CLI_MESS_OPTION_WARN,
	TOTAL_MESSAGES
};

void throw_cli_mess(enum CLIENT_MESSAGES mess);